### ISSUE TITLE
Unable to migrate Protobuf schema in schema registry. 

### ISSUE THREAD

**Issue by langvatn** [Aiven-Open/karapace#505]
# What happened?

We try to update the protobuf schema only to get an http status code 500. The only change in the schema is a new optional int32 field that should be backwards compatible.

```
package com.company.fisk.libs.schemas.lakselus.v1;

import "google/protobuf/timestamp.proto";

option java_package = "com.company.fisk.libs.schemas.lakselus.v1";
option java_multiple_files = true;

message LakselusSchema {
  .google.protobuf.Timestamp innsendingstidspunkt = 1;
  int32 rapporteringsuke = 2;
  string ekstern_referanse = 3;
  string kildesystem = 4;
  optional string kommentar = 5;
  .com.company.fisk.libs.schemas.lakselus.v1.Rapporterer rapporterer = 6;
  .com.company.fisk.libs.schemas.lakselus.v1.MekaniskFjerningAvLakselus mekanisk_fjerning_av_lakselus = 7;
  .com.company.fisk.libs.schemas.lakselus.v1.Behandling badebehandling = 8;
  .com.company.fisk.libs.schemas.lakselus.v1.Behandling forbehandling = 9;
  .com.company.fisk.libs.schemas.lakselus.v1.UtsettRensefisk utsett_rensefisk = 10;
  .com.company.fisk.libs.schemas.lakselus.v1.Resistens resistens = 11;
  .com.company.fisk.libs.schemas.lakselus.v1.Foelsomhetsundersoekelse foelsomhetsundersoekelse = 12;
  .com.company.fisk.libs.schemas.lakselus.v1.Lusetelling lusetelling = 13;
  .com.company.fisk.libs.schemas.lakselus.v1.Selskap selskap = 14;
  .com.company.fisk.libs.schemas.lakselus.v1.Lokalitet lokalitet = 15;
  string intern_referanse = 16;
}
message Behandling {
  bool utfoert = 1;
  optional bool hele_lokaliteten = 2;
  repeated .com.company.fisk.libs.schemas.lakselus.v1.VirkestoffInformasjon virkestoffer = 3;
  optional .google.protobuf.Timestamp startdato = 4;
  optional .google.protobuf.Timestamp sluttdato = 5;
}
message VirkestoffInformasjon {
  double mengde = 1;
  double styrke = 2;
  int64 virkestoff = 3;
}
message MekaniskFjerningAvLakselus {
  bool utfoert = 1;
  optional bool hele_lokaliteten = 2;
  optional string metode = 3;
}
message Rensefisk {
  int64 art = 1;
  int64 utsatt = 2;
}
message UtsettRensefisk {
  bool utfoert = 1;
  optional bool hele_lokaliteten = 2;
  repeated .com.company.fisk.libs.schemas.lakselus.v1.Rensefisk rensefisker = 3;
}
message MistankeOmResistens {
  int64 virkestoff = 1;
  int64 aarsak = 2;
}
message Resistens {
  bool mistanke = 1;
  repeated .com.company.fisk.libs.schemas.lakselus.v1.MistankeOmResistens mistanke_om_resistens = 2;
}
message Foelsomhetsundersoekelse {
  bool utfoert = 1;
  optional .google.protobuf.Timestamp dato_test_utfoert = 2;
  optional string laboratorium = 3;
  repeated .com.company.fisk.libs.schemas.lakselus.v1.FoelsomhetsundersoekelseTestresultat testresultater = 4;
}
message FoelsomhetsundersoekelseTestresultat {
  int64 virkestoff = 1;
  int64 testresultat = 2;
}
message Selskap {
  string organisasjonsnummer = 1;
  string organisasjonsnavn = 2;
}
message Lokalitet {
  int32 lokalitetsnummer = 1;
  string lokalitetsnavn = 2;
}
message Lusetelling {
  double sjoetemperatur = 1;
  optional double voksne_hunnlus = 2;
  optional double bevegelige_lus = 3;
  optional double fastsittende_lus = 4;
}
message Rapporterer {
  string id = 1;
  string navn = 2;
  string epost = 3;
  string mobilnummer = 4;
  optional string fagsystem = 5;
}
```
to
```
package com.company.fisk.libs.schemas.lakselus.v1;

import "google/protobuf/timestamp.proto";

option java_package = "com.company.fisk.libs.schemas.lakselus.v1";
option java_multiple_files = true;

message LakselusSchema {
  .google.protobuf.Timestamp innsendingstidspunkt = 1;
  int32 rapporteringsuke = 2;
  string ekstern_referanse = 3;
  string kildesystem = 4;
  optional string kommentar = 5;
  .com.company.fisk.libs.schemas.lakselus.v1.Rapporterer rapporterer = 6;
  .com.company.fisk.libs.schemas.lakselus.v1.MekaniskFjerningAvLakselus mekanisk_fjerning_av_lakselus = 7;
  .com.company.fisk.libs.schemas.lakselus.v1.Behandling badebehandling = 8;
  .com.company.fisk.libs.schemas.lakselus.v1.Behandling forbehandling = 9;
  .com.company.fisk.libs.schemas.lakselus.v1.UtsettRensefisk utsett_rensefisk = 10;
  .com.company.fisk.libs.schemas.lakselus.v1.Resistens resistens = 11;
  .com.company.fisk.libs.schemas.lakselus.v1.Foelsomhetsundersoekelse foelsomhetsundersoekelse = 12;
  .com.company.fisk.libs.schemas.lakselus.v1.Lusetelling lusetelling = 13;
  .com.company.fisk.libs.schemas.lakselus.v1.Selskap selskap = 14;
  .com.company.fisk.libs.schemas.lakselus.v1.Lokalitet lokalitet = 15;
  string intern_referanse = 16;
  optional int32 source_version = 17;
}
message Behandling {
  bool utfoert = 1;
  optional bool hele_lokaliteten = 2;
  repeated .com.company.fisk.libs.schemas.lakselus.v1.VirkestoffInformasjon virkestoffer = 3;
  optional .google.protobuf.Timestamp startdato = 4;
  optional .google.protobuf.Timestamp sluttdato = 5;
}
message VirkestoffInformasjon {
  double mengde = 1;
  double styrke = 2;
  int64 virkestoff = 3;
}
message MekaniskFjerningAvLakselus {
  bool utfoert = 1;
  optional bool hele_lokaliteten = 2;
  optional string metode = 3;
}
message Rensefisk {
  int64 art = 1;
  int64 utsatt = 2;
}
message UtsettRensefisk {
  bool utfoert = 1;
  optional bool hele_lokaliteten = 2;
  repeated .com.company.fisk.libs.schemas.lakselus.v1.Rensefisk rensefisker = 3;
}
message MistankeOmResistens {
  int64 virkestoff = 1;
  int64 aarsak = 2;
}
message Resistens {
  bool mistanke = 1;
  repeated .com.company.fisk.libs.schemas.lakselus.v1.MistankeOmResistens mistanke_om_resistens = 2;
}
message Foelsomhetsundersoekelse {
  bool utfoert = 1;
  optional .google.protobuf.Timestamp dato_test_utfoert = 2;
  optional string laboratorium = 3;
  repeated .com.company.fisk.libs.schemas.lakselus.v1.FoelsomhetsundersoekelseTestresultat testresultater = 4;
}
message FoelsomhetsundersoekelseTestresultat {
  int64 virkestoff = 1;
  int64 testresultat = 2;
}
message Selskap {
  string organisasjonsnummer = 1;
  string organisasjonsnavn = 2;
}
message Lokalitet {
  int32 lokalitetsnummer = 1;
  string lokalitetsnavn = 2;
}
message Lusetelling {
  double sjoetemperatur = 1;
  optional double voksne_hunnlus = 2;
  optional double bevegelige_lus = 3;
  optional double fastsittende_lus = 4;
}
message Rapporterer {
  string id = 1;
  string navn = 2;
  string epost = 3;
  string mobilnummer = 4;
  optional string fagsystem = 5;
}
```

The only difference is `optional int32 source_version = 17;`

# What did you expect to happen?

The new schema is accepted in the schema registry.

# What else do we need to know?

from the Aiven logs:

```
karapace MainThread ERROR Internal server error
File "/usr/lib/python3.10/site-packages/karapace/compatibility/protobuf/checks.py", line 8, in check_protobuf_schema_compatibility
Traceback (most recent call last):
self.compare_message(self_type, other_type, result, types)
File "/usr/lib/python3.10/site-packages/karapace/compatibility/__init__.py", line 75, in check_protobuf_compatibility
File "/usr/lib/python3.10/site-packages/karapace/protobuf/field_element.py", line 134, in compare_type
self.compare_type(ProtoType.get2(self.element_type), ProtoType.get2(other.element_type), other.label, result, types)
File "/usr/lib/python3.10/site-packages/karapace/protobuf/schema.py", line 165, in compare
File "/usr/lib/python3.10/site-packages/karapace/protobuf/field_element.py", line 146, in compare_message
karapace.schema_registry MainThread INFO Writing new schema locally since we're the master
File "/usr/lib/python3.10/site-packages/karapace/protobuf/message_element.py", line 126, in compare
File "/usr/lib/python3.10/site-packages/karapace/protobuf/field_element.py", line 146, in compare_message
result = check_compatibility(
karapace MainThread ERROR Internal server error
result = check_protobuf_compatibility(
self.compare_type(ProtoType.get2(self.element_type), ProtoType.get2(other.element_type), other.label, result, types)
File "/usr/lib/python3.10/site-packages/karapace/protobuf/field_element.py", line 134, in compare_type
File "/usr/lib/python3.10/site-packages/karapace/protobuf/field_element.py", line 78, in compare
AttributeError: 'NoneType' object has no attribute 'type_element'
File "/usr/lib/python3.10/site-packages/karapace/schema_registry.py", line 342, in write_new_schema_local
schema_id = await self.schema_registry.write_new_schema_local(subject, new_schema)
File "/usr/lib/python3.10/site-packages/karapace/protobuf/proto_file_element.py", line 154, in compare
self_types[name].compare(other_types[name], result, compare_types)
```

**Comment by tvainika** [comment]
I think #630 fixed this issue too. Sorry for not looking sooner this one.
