### ISSUE TITLE
Schema registry doesnt start doe to snappy compression error

### ISSUE THREAD

**Issue by avinashsingh77** [Aiven-Open/karapace#766]
# What happened?

When I try to launch a container using ghcr.io/aiven-open/karapace:latest, I get an error. 
Snippet of the error as follows:

karapace.schema_reader  schema-reader   ERROR           Unexpected exception in schema reader loop
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/karapace/schema_reader.py", line 228, in run
    self.handle_messages()
  File "/venv/lib/python3.10/site-packages/karapace/schema_reader.py", line 295, in handle_messages
    raw_msgs = self.consumer.poll(timeout_ms=self.timeout_ms)
  File "/venv/lib/python3.10/site-packages/kafka/consumer/group.py", line 659, in poll
    records = self._poll_once(remaining, max_records, update_offsets=update_offsets)
  File "/venv/lib/python3.10/site-packages/kafka/consumer/group.py", line 690, in _poll_once
    records, partial = self._fetcher.fetched_records(max_records, update_offsets=update_offsets)
  File "/venv/lib/python3.10/site-packages/kafka/consumer/fetcher.py", line 344, in fetched_records
    self._next_partition_records = self._parse_fetched_data(completion)
  File "/venv/lib/python3.10/site-packages/kafka/consumer/fetcher.py", line 818, in _parse_fetched_data
    unpacked = list(self._unpack_message_set(tp, records))
  File "/venv/lib/python3.10/site-packages/kafka/consumer/fetcher.py", line 467, in _unpack_message_set
    for record in batch:
  File "/venv/lib/python3.10/site-packages/kafka/record/default_records.py", line 276, in __iter__
    self._maybe_uncompress()
  File "/venv/lib/python3.10/site-packages/kafka/record/default_records.py", line 183, in _maybe_uncompress
    self._assert_has_codec(compression_type)
  File "/venv/lib/python3.10/site-packages/kafka/record/default_records.py", line 118, in _assert_has_codec
    raise UnsupportedCodecError(
kafka.errors.UnsupportedCodecError: UnsupportedCodecError: Libraries for snappy compression codec not found

# What did you expect to happen?

I expected schema registry to be up and running on my local on specified port.

# What else do we need to know?

If I add the following
"libsnappy-dev" in Dockerfile line no. 38
"python-snappy==0.6.1" in requirements.in and requirements.txt
and build the image again locally and use the local copy of image, it works fine.
Schema registry in up and running on my local.

If this is a recommended fix, I can submit a PR.

**Comment by avinashsingh77** [comment]
Hey @tvainika , any idea when will the PR #773 be merged? I want to test this issue.

**Comment by avinashsingh77** [comment]
@matyaskuti I see `develop` tag was built after this issue was closed. When do we expect `latest` tag to have this fix?
